version: "3"
services:
  # database:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=1234
  #     - PGDATA=/data/postgres
  #     - POSTGRES_DB=iot
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - database:/var/lib/pgql

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      - docker_network
  mqtt-ws-broker:
    build: .
    env_file:
      - .env.docker
    ports:
      - "1883:1883"
      - "8080:8080"
    networks:
      - docker_network
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana-server
  #   restart: always
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=1234abcd@@
  #     - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-mqtt-datasource
  #     - GF_SERVER_PROTOCOL=http
  #     - GF_SERVER_DOMAIN=uraa.asia
  #     - GF_SERVER_ROOT_URL=https://uraa.asia/grafana
  #     - GF_SERVER_SERVE_FROM_SUB_PATH=true
  #   ports:
  #     - 3001:3000
  #   volumes:
  #     - grafana-plugin:/grafana_plugins:/var/lib/grafana/plugins
  #     - grafana-data:/grafana_data:/var/lib/grafana
  #   networks:
  #     - docker_network
volumes:
  # grafana-plugin:
  #   driver: local
  # grafana-data:
  #   driver: local
  cache:
    driver: local
  # database:
  #   driver: local
networks:
  docker_network:
    driver: bridge
